name: Compile Modpack

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Build
        shell: bash
        run: chmod +x ${{ github.workspace }}/build.sh && ${{ github.workspace }}/build.sh

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifact: "*.mrpack"
          token: ${{ secrets.RELEASE_TOKEN }}
