name: Compile Modpack

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        shell: bash
        run: chmod +x ${{ github.workspace }}/build.sh && ${{ github.workspace }}/build.sh
